<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJseffxn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJseffxn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJseffxn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJseffxn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJseffxn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jseffxn',
    'container.build_id' => 'ce1751ca',
    'container.build_time' => 1517851692,
));
