<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\DefaultController:newAction' => function () {
    return ${($_ = isset($this->services['service_locator.qhm8twu']) ? $this->services['service_locator.qhm8twu'] : $this->load(__DIR__.'/getServiceLocator_Qhm8twuService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController:sendEmail' => function () {
    return ${($_ = isset($this->services['service_locator.40sjrlg']) ? $this->services['service_locator.40sjrlg'] : $this->load(__DIR__.'/getServiceLocator_40sjrlgService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::newAction' => function () {
    return ${($_ = isset($this->services['service_locator.qhm8twu']) ? $this->services['service_locator.qhm8twu'] : $this->load(__DIR__.'/getServiceLocator_Qhm8twuService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::sendEmail' => function () {
    return ${($_ = isset($this->services['service_locator.40sjrlg']) ? $this->services['service_locator.40sjrlg'] : $this->load(__DIR__.'/getServiceLocator_40sjrlgService.php')) && false ?: '_'};
})));
