<?php

namespace AppBundle\Repository\Form;

/**
 * FormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
