AppBundle\Entity\Form\Formulaire:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Form\FormulaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        city:
            type: string
            length: 255
        favCity:
            type: string
            length: 255
        age:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
